version: "3.7"

services:
  wifi-card:
    container_name: wifi-card
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
