version: 2.1
jobs:
  build:
    docker:
      - image: arm64v8/node:lts-alpine
    steps:
      - checkout
      - setup_remote_docker
      - run: make build-prod

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
