version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: make build-prod-amd64

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
